name: google_wallet_clone
description: "Google Wallet Clone."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  lottie: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  pixel_perfect: ^1.1.3
  google_fonts: ^6.1.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  assets:
    - assets/


  uses-material-design: true